include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-inference: false

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    directives_ordering: false
    avoid_positional_boolean_parameters: false
